services:
  backend:
    build:
      context: ../..
      dockerfile: Dockerfile
    env_file:
      - ./backend.env
    depends_on:
      - telethon
      - crawlee
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped

  telethon:
    build:
      context: ../../telethon-service
      dockerfile: Dockerfile
    env_file:
      - ./telethon.env
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped

  crawlee:
    build:
      context: ../../crawlee-service
      dockerfile: Dockerfile
    env_file:
      - ./crawlee.env
    ports:
      - "127.0.0.1:8002:8002"
    restart: unless-stopped

